---
abstract: 'Simple, compact and correct param-checking functions'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.52
  File::Spec: 0.80
  Test::More: 0.42
configure_requires:
  ExtUtils::CBuilder: 0.27
  ExtUtils::MakeMaker: 6.52
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Util
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: 1.18
  perl: 5.00503
version: 1.07
